export const BEFORE_RESULT = 'BEFORE_RESULT';
export const SHORTEN_URL = 'SHORTEN_URL';
export const ERROR = 'ERROR';
export const RESET = 'RESET';
export const PERSIST = 'PERSIST';
export const RETRIEVE = 'RETRIEVE';
export const BUTTON_LOADER = 'BUTTON_LOADER';


export const BEFORE_CLICK_ANALYTICS_RESULT = 'BEFORE_CLICK_ANALYTICS_RESULT';
export const CLICK_ANALYTICS = 'CLICK_ANALYTICS';
export const CLICK_ANALYTICS_ERROR = 'CLICK_ANALYTICS_ERROR';


export const BEFORE_GENERAL_ANALYTICS_RESULT = 'BEFORE_GENERAL_ANALYTICS_RESULT';
export const GENERAL_ANALYTICS = 'GENERAL_ANALYTICS';
export const GENERAL_ANALYTICS_ERROR = 'GENERAL_ANALYTICS_ERROR';


export const BEFORE_LIST_RESULT = 'BEFORE_LIST_RESULT';
export const LIST_ERROR = 'LIST_ERROR';